# Cloudflare Workers and Pages GitHub App configuration
# This file controls when the Cloudflare bot runs deployments

# Disable automatic deployments for pull requests
deployment:
  pull_requests:
    enabled: false
  
  # Only deploy on pushes to main branch
  branches:
    - main
