name = "cologne"
compatibility_date = "2025-06-05"

[site]
bucket = "./dist"

# Environment variables can be set in the dashboard
# [vars]
# GITHUB_TOKEN = "your-token-here"  # DO NOT commit actual tokens

# Routes are configured in the dashboard
# route = "cologne.ravers.workers.dev/*"

# Build configuration
[build]
command = "npm run build"

# Development settings
[dev]
port = 8787
local_protocol = "http"
