name = "cologne"
compatibility_date = "2025-06-05"
main = "dist/_worker.js"

[site]
bucket = "./dist"

# Secrets Store binding will be configured in the dashboard
# [[secrets]]
# binding = "SECRETS"

# Routes are configured in the dashboard
# route = "cologne.ravers.workers.dev/*"

# Build configuration
[build]
command = "npm run build"

# Development settings
[dev]
port = 8787
local_protocol = "http"
