name = "cologne"
compatibility_date = "2025-06-05"
main = "dist/_worker.js"

[site]
bucket = "./dist"

# Build configuration
[build]
command = "npm run build"

# Development settings
[dev]
port = 8787
local_protocol = "http"
